# Generated by Django 3.0.8 on 2021-07-02 01:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0006_auto_20210630_1758'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Comment_old',
        ),
    ]
